### ISSUE TITLE
Handle java.net.UnknownHostException: www.lvz.de

### ISSUE THREAD

**Issue by sepe81** [CodeforLeipzig/lvz-viz#61]
```
2021-02-01 12:39:23.797 ERROR 1 --- [Executor-193559] d.c.le.crawler.LvzPoliceTickerCrawler    : java.net.UnknownHostException: www.lvz.de

java.net.UnknownHostException: www.lvz.de
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:184) ~[na:1.8.0_265]
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392) ~[na:1.8.0_265]
	at java.net.Socket.connect(Socket.java:607) ~[na:1.8.0_265]
	at sun.net.NetworkClient.doConnect(NetworkClient.java:175) ~[na:1.8.0_265]
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:463) ~[na:1.8.0_265]
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:558) ~[na:1.8.0_265]
	at sun.net.www.http.HttpClient.<init>(HttpClient.java:242) ~[na:1.8.0_265]
	at sun.net.www.http.HttpClient.New(HttpClient.java:339) ~[na:1.8.0_265]
	at sun.net.www.http.HttpClient.New(HttpClient.java:357) ~[na:1.8.0_265]
	at sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:1226) ~[na:1.8.0_265]
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1162) ~[na:1.8.0_265]
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1056) ~[na:1.8.0_265]
	at sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:990) ~[na:1.8.0_265]
	at org.jsoup.helper.HttpConnection$Response.execute(HttpConnection.java:730) ~[jsoup-1.12.1.jar!/:na]
	at org.jsoup.helper.HttpConnection$Response.execute(HttpConnection.java:705) ~[jsoup-1.12.1.jar!/:na]
	at org.jsoup.helper.HttpConnection.execute(HttpConnection.java:295) ~[jsoup-1.12.1.jar!/:na]
	at org.jsoup.helper.HttpConnection.get(HttpConnection.java:284) ~[jsoup-1.12.1.jar!/:na]
	at de.codefor.le.crawler.LvzPoliceTickerCrawler.crawlNewsFromPage(LvzPoliceTickerCrawler.java:78) ~[classes!/:na]
	at de.codefor.le.crawler.LvzPoliceTickerCrawler.execute(LvzPoliceTickerCrawler.java:62) ~[classes!/:na]
	at de.codefor.le.crawler.LvzPoliceTickerCrawler$$FastClassBySpringCGLIB$$247f5e4c.invoke(<generated>) [classes!/:na]
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204) [spring-core-4.3.9.RELEASE.jar!/:4.3.9.RELEASE]
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:738) [spring-aop-4.3.9.RELEASE.jar!/:4.3.9.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157) [spring-aop-4.3.9.RELEASE.jar!/:4.3.9.RELEASE]
	at org.springframework.aop.interceptor.AsyncExecutionInterceptor$1.call(AsyncExecutionInterceptor.java:115) [spring-aop-4.3.9.RELEASE.jar!/:4.3.9.RELEASE]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_265]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_265]

2021-02-01 12:39:23.797  INFO 1 --- [Executor-193559] d.c.le.crawler.LvzPoliceTickerCrawler    : Finished crawling page 193492 in 0 ms.
```

**Comment by sepe81** [comment]
This is solved with https://github.com/CodeforLeipzig/lvz-viz/commit/afee5b3f5483d1d9b8da5086e92f834daa89078e and looks like the following now:

```
2021-05-07 14:02:49.818  INFO 75298 --- [   scheduling-1] de.codefor.le.crawler.CrawlScheduler     : Start crawling police ticker.
2021-05-07 14:02:49.832  INFO 75298 --- [         task-1] d.c.le.crawler.LvzPoliceTickerCrawler    : Start crawling http://www.lvz.de/Leipzig/Polizeiticker/Polizeiticker-Leipzig/1#anchor.
2021-05-07 14:02:49.917  INFO 75298 --- [         task-1] d.c.le.crawler.LvzPoliceTickerCrawler    : Finished crawling page 1 in 85 ms.
2021-05-07 14:02:49.921 ERROR 75298 --- [   scheduling-1] o.s.s.s.TaskUtils$LoggingErrorHandler    : Unexpected error occurred in scheduled task

java.util.concurrent.ExecutionException: java.io.UncheckedIOException: Request for url http://www.lvz.de/Leipzig/Polizeiticker/Polizeiticker-Leipzig/1#anchor failed.
        at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[na:na]
        at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191) ~[na:na]
        at de.codefor.le.crawler.CrawlScheduler.crawl(CrawlScheduler.java:48) ~[classes!/:na]
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:na]
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
        at java.base/java.lang.reflect.Method.invoke(Method.java:566) ~[na:na]
        at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:84) ~[spring-context-5.2.12.RELEASE.jar!/:5.2.12.RELEASE]
        at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) ~[spring-context-5.2.12.RELEASE.jar!/:5.2.12.RELEASE]
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) ~[na:na]
        at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305) ~[na:na]
        at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305) ~[na:na]
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[na:na]
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[na:na]
        at java.base/java.lang.Thread.run(Thread.java:829) ~[na:na]
Caused by: java.io.UncheckedIOException: Request for url http://www.lvz.de/Leipzig/Polizeiticker/Polizeiticker-Leipzig/1#anchor failed.
        at de.codefor.le.crawler.LvzPoliceTickerCrawler.crawlNewsFromPage(LvzPoliceTickerCrawler.java:77) ~[classes!/:na]
        at de.codefor.le.crawler.LvzPoliceTickerCrawler.execute(LvzPoliceTickerCrawler.java:61) ~[classes!/:na]
        at de.codefor.le.crawler.LvzPoliceTickerCrawler$$FastClassBySpringCGLIB$$247f5e4c.invoke(<generated>) ~[classes!/:na]
        at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218) ~[spring-core-5.2.12.RELEASE.jar!/:5.2.12.RELEASE]
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:771) ~[spring-aop-5.2.12.RELEASE.jar!/:5.2.12.RELEASE]
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163) ~[spring-aop-5.2.12.RELEASE.jar!/:5.2.12.RELEASE]
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:749) ~[spring-aop-5.2.12.RELEASE.jar!/:5.2.12.RELEASE]
        at org.springframework.aop.interceptor.AsyncExecutionInterceptor.lambda$invoke$0(AsyncExecutionInterceptor.java:115) ~[spring-aop-5.2.12.RELEASE.jar!/:5.2.12.RELEASE]
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[na:na]
        ... 3 common frames omitted
Caused by: java.net.UnknownHostException: www.lvz.de
        at java.base/java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:220) ~[na:na]
        at java.base/java.net.Socket.connect(Socket.java:609) ~[na:na]
        at java.base/sun.net.NetworkClient.doConnect(NetworkClient.java:177) ~[na:na]
        at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:474) ~[na:na]
        at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:569) ~[na:na]
        at java.base/sun.net.www.http.HttpClient.<init>(HttpClient.java:242) ~[na:na]
        at java.base/sun.net.www.http.HttpClient.New(HttpClient.java:341) ~[na:na]
        at java.base/sun.net.www.http.HttpClient.New(HttpClient.java:362) ~[na:na]
        at java.base/sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:1253) ~[na:na]
        at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1187) ~[na:na]
        at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1081) ~[na:na]
        at java.base/sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:1015) ~[na:na]
        at org.jsoup.helper.HttpConnection$Response.execute(HttpConnection.java:732) ~[jsoup-1.13.1.jar!/:na]
        at org.jsoup.helper.HttpConnection$Response.execute(HttpConnection.java:707) ~[jsoup-1.13.1.jar!/:na]
        at org.jsoup.helper.HttpConnection.execute(HttpConnection.java:297) ~[jsoup-1.13.1.jar!/:na]
        at org.jsoup.helper.HttpConnection.get(HttpConnection.java:286) ~[jsoup-1.13.1.jar!/:na]
        at de.codefor.le.crawler.LvzPoliceTickerCrawler.crawlNewsFromPage(LvzPoliceTickerCrawler.java:75) ~[classes!/:na]
        ... 11 common frames omitted
```
